# Generated by Django 4.2.4 on 2024-05-26 20:17

from django.db import migrations, models
import django.db.models.deletion
import mainApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_user_is_admin_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('vid_file', models.FileField(upload_to='uploads/', validators=[mainApp.models.validate_video_file])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('prob_set', models.FileField(upload_to='uploads/', validators=[mainApp.models.validate_pdf_file])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='mainApp.course')),
            ],
        ),
    ]
