# Generated by Django 4.2.4 on 2024-05-27 09:03

from django.db import migrations, models
import mainApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='img_file',
            field=models.FileField(blank=True, null=True, upload_to='assets/', validators=[mainApp.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='prob_set',
            field=models.FileField(upload_to='assets/', validators=[mainApp.models.validate_pdf_file]),
        ),
    ]
