# Generated by Django 4.2.4 on 2024-05-27 12:08

from django.db import migrations, models
import mainApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_course_img_file_alter_upload_prob_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='prob_set',
            field=models.FileField(blank=True, null=True, upload_to='assets/', validators=[mainApp.models.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='vid_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[mainApp.models.validate_video_file]),
        ),
    ]
