# Generated by Django 4.2.4 on 2024-05-28 11:29

from django.db import migrations, models
import mainApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_rename_prob_set_upload_probset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='probSet',
            field=models.FileField(blank=True, null=True, upload_to='pdf/', validators=[mainApp.models.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='vidFile',
            field=models.FileField(blank=True, null=True, upload_to='video/', validators=[mainApp.models.validate_video_file]),
        ),
    ]
