# Generated by Django 4.2.4 on 2024-05-28 11:32

from django.db import migrations, models
import mainApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_alter_upload_probset_alter_upload_vidfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='probSet',
            field=models.FileField(blank=True, null=True, upload_to='mainApp/static/pdf/', validators=[mainApp.models.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='vidFile',
            field=models.FileField(blank=True, null=True, upload_to='mainApp/static/video/', validators=[mainApp.models.validate_video_file]),
        ),
    ]
