# Generated by Django 4.2.4 on 2024-06-03 07:56

from django.db import migrations, models
import mainApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_alter_upload_probset_alter_upload_vidfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='img_file',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='image/', validators=[mainApp.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
